[build]
  command = "npm install"
  publish = "."

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.js"
  status = 200

[functions]
  directory = "."
  node_bundler = "esbuild" 